apps/controlador/urls.py
from django.urls import path
from django.conf.urls import url
from . import views
from django.contrib.auth.decorators import login_required

urlpatterns = [

    path('listar', login_required(views.ControladorList.as_view()), name='controlador_listar'),
    path('create', login_required(views.ControladorCreate.as_view()), name='controlador_crear'),
    path('edit/<int:pk>', login_required(views.ControladorUpdate.as_view()), name='controlador_editar'),
    path('delete/<int:pk>', login_required(views.ControladorDelete.as_view()), name='controlador_delete'),
]

proyecto_django/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [

    path(r'periodos/', include('apps.periodos.urls')),


    path(r'accounts/', include('apps.registration.urls')),
    path(r'admin/', admin.site.urls),
    path(r'dashboard/', include('apps.dashboard.urls')),
    path(r'estructura/', include('apps.estructura.urls')),
    path(r'objetivos/', include('apps.objetivos.urls')),
    path(r'horas/', include('apps.gestion_horas.urls')),
    path(r'jefaturas/', include('apps.jefaturas.urls')),
    path(r'feriados/', include('apps.feriados.urls')),
    path(r'ejes/', include('apps.eje.urls')),
    path(r'vista_objetivos/', include('apps.vista_objetivos.urls')),
    path(r'familiadecargos/', include('apps.familia_cargo.urls')),

    path(r'periodicidad/', include('apps.periodicidad.urls')),
    path(r'productos/', include('apps.productos.urls')),
    path(r'estado_flujo/', include('apps.estado_flujo.urls')),
    path(r'controlador/', include('apps.controlador.urls')),
    path(r'actividades/', include('apps.actividades.urls')),
    path(r'valida_plan/', include('apps.valida_plan.urls')),
    path(r'valida_plan2/', include('apps.valida_plan2.urls')),
    path(r'perfiles/', include('apps.perfiles.urls')),

    path(r'revision_planificacion/', include('apps.revision_planificacion.urls')),
    path(r'seguimiento_formula/', include('apps.seguimiento_formula.urls')),
    path(r'reportes/', include('apps.reportes.urls')),
    path(r'valida_seguimiento/', include('apps.valida_seguimiento.urls')),
    path(r'planificacion_admin/', include('apps.planificacion_admin.urls')),





]





apps/controlador/models.py
from django.db import models
from apps.periodos.models import Glo_Periodos
from apps.estado_flujo.models import Glo_EstadoFlujo
from apps.jefaturas.models import Ges_Jefatura
from apps.estructura.models import Ges_Niveles
from django.utils import timezone as tz
from django.contrib.auth.models import User
from apps.estado_plan.models import Glo_EstadoPlan
# Create your models here.

class Ges_Controlador(models.Model):
    id_periodo = models.ForeignKey(Glo_Periodos, on_delete=models.PROTECT)
    id_jefatura= models.ForeignKey(Ges_Jefatura, on_delete=models.PROTECT, null=True)
    nivel_inicial= models.IntegerField()
    estado_flujo = models.ForeignKey(Glo_EstadoFlujo, on_delete=models.PROTECT)
    fecha_ultima_modificacion= models.DateField(auto_now=True)
    jefatura_primerarevision = models.ForeignKey(Ges_Jefatura, on_delete=models.PROTECT, null=True,
                                                 related_name="jefatura_primerarevision")
    jefatura_segundarevision = models.ForeignKey(Ges_Jefatura, on_delete=models.PROTECT, null=True,
                                                 related_name="jefatura_segundarevision")
    analista_asignado  = models.ForeignKey(User, on_delete=models.PROTECT, null=True, blank=True)
    id_estado_plan = models.ForeignKey(Glo_EstadoPlan, on_delete=models.PROTECT, null=True, blank=True, default=1)



apps/controlador/forms.py
from django import forms
from apps.controlador.models import Ges_Controlador
from apps.jefaturas.models import Ges_Jefatura
from apps.jefaturas.models import Ges_Jefatura as Gj
from django.contrib.auth.models import User, Group
from django.db.models import Q

class controladorFlujoForm(forms.ModelForm):

    def __init__(self, id_periodo ,*args, **kwargs):
        self.request = kwargs.pop('request', None)
        super(controladorFlujoForm, self).__init__(*args, **kwargs)
        qs= Ges_Controlador.objects.all().values_list('id_jefatura', flat=True)


        jefaturas_pefiles = list(User.objects.values_list('id', flat=True).filter(groups__in=Group.objects.filter(Q(id='4') | Q(id='3'))))


        self.fields['id_jefatura'].queryset = Ges_Jefatura.objects.filter(id_periodo=id_periodo).exclude(Q(id__in=qs) | Q(id_user__in=jefaturas_pefiles))

    class Meta:
        model = Ges_Controlador

        fields = [
            'id_jefatura',

        ]


        widgets = {

            'id_jefatura': forms.Select(attrs={'class': 'form-control', 'id':'siteID'}),


        }


class GestionControladorUpdateForm(forms.ModelForm):

    def __init__(self,nivel_jefatura ,*args, **kwargs):
        self.request = kwargs.pop('request', None)
        super(GestionControladorUpdateForm, self).__init__(*args, **kwargs)
        self.fields['jefatura_primerarevision'].queryset = Gj.objects.filter(id_nivel_id=nivel_jefatura)



    class Meta:
        model = Ges_Controlador
        fields = [
            'estado_flujo',
            'id_jefatura',
            'jefatura_primerarevision',


        ]

        widgets = {
            'estado_flujo': forms.Select(attrs={'class': 'form-control', 'readonly':'readonly'}),
            'jefatura_primerarevision': forms.Select(attrs={'class': 'form-control'}),
            'id_jefatura': forms.Select(attrs={'class': 'form-control', 'readonly':'readonly'}),
        }

apps/controlador/views.py
import smtplib

from django.core import mail
from django.http import HttpResponseRedirect
from django.contrib import messages
from django.contrib.auth.models import User, Group
from django.contrib.messages.views import SuccessMessageMixin
from django.db.models.deletion import ProtectedError
from django.db.models import Q
from django.utils.module_loading import import_string
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from apps.actividades.models import Ges_Actividad
from apps.controlador.models import Ges_Controlador
from apps.periodos.models import Glo_Periodos
from apps.controlador.forms import controladorFlujoForm, GestionControladorUpdateForm
from apps.jefaturas.models import Ges_Jefatura
from apps.estructura.models import Ges_Niveles, Ges_CuartoNivel, Ges_TercerNivel, Ges_SegundoNivel, Ges_PrimerNivel
from apps.estado_flujo.models import Glo_EstadoFlujo
from datetime import date
from django.db.models import Case, CharField, Value, When
from django.contrib import messages
from django.core.mail import EmailMessage,send_mass_mail
from django.core.mail import send_mail, EmailMultiAlternatives
from django.template.loader import get_template
from django.template import Context
from apps.valida_plan.models import Ges_Observaciones
from apps.valida_plan2.models import Ges_Observaciones_sr

from django.conf import settings

from apps.registration.models import logEventos


class ControladorList(ListView):
    model = Ges_Controlador
    template_name = 'controlador/controlador_list.html'

    def get_context_data(self,  **kwargs):
        context = super(ControladorList, self).get_context_data(**kwargs)
        id_usuario_actual= self.request.user.id #obtiene id usuario actual

        try:
            periodo_actual = Glo_Periodos.objects.get(id_estado=1)
        except Glo_Periodos.DoesNotExist:
            return None

        lista_horas = Ges_Controlador.objects.filter(id_periodo=periodo_actual.id)
        context['object_list'] = lista_horas
        return context



class ControladorCreate(SuccessMessageMixin, CreateView):
    model = Ges_Controlador
    form_class = controladorFlujoForm
    template_name = 'controlador/controlador_form.html'

    def get_form_kwargs(self, **kwargs):
        kwargs = super(ControladorCreate, self).get_form_kwargs()
        try:
            periodo_actual = Glo_Periodos.objects.get(id_estado=1)
        except Glo_Periodos.DoesNotExist:
            return None
        kwargs['id_periodo'] = periodo_actual
        return kwargs

    def post(self, request, *args, **kwargs):
        form_class = self.get_form_class()
        form = self.get_form(form_class)

        jefatura = request.POST['id_jefatura']
        nivel_jefatura= Ges_Jefatura.objects.get(id=jefatura)
        nivel_inicial = Ges_Niveles.objects.get(id=nivel_jefatura.id_nivel_id)

        user_id_jefatura=nivel_jefatura.id_user

        periodo= Glo_Periodos.objects.get(id_estado=1)
        estado_flujo = Glo_EstadoFlujo.objects.get(estado=2)

        if form.is_valid():
            form.instance.nivel_inicial=nivel_inicial.orden_nivel
            form.instance.id_periodo = periodo
            form.instance.estado_flujo= estado_flujo
            form.instance.fecha_ultima_modificacion= date.today()



            form.save()

            g = Group.objects.get(id=1)
            g.user_set.add(user_id_jefatura)

            request.session['message_class'] = "alert alert-success"
            messages.success(self.request, "Los datos fueron creados correctamente!")
            return HttpResponseRedirect('/controlador/listar')
        else:
            request.session['message_class'] = "alert alert-danger"
            messages.error(self.request, "Error interno: No se ha creado el registro. Comuníquese con el administrador.")
            return HttpResponseRedirect('/controlador/listar')


class ControladorDelete(SuccessMessageMixin, DeleteView ):
    model = Ges_Controlador
    template_name = 'controlador/controlador_delete.html'

    def delete(self, request, *args, **kwargs):
        obj = self.get_object()
        try:

            id_controlador = self.kwargs['pk']
            nivel_jefatura = Ges_Controlador.objects.get(id=id_controlador)
            user_id_jefatura = nivel_jefatura.id_jefatura.id_user



            obj.delete()

            g = Group.objects.get(user=user_id_jefatura)
            g.user_set.remove(user_id_jefatura)




            request.session['message_class'] = "alert alert-success"
            messages.success(self.request, "El registro fue eliminado correctamente!")
            return HttpResponseRedirect('/controlador/listar')

        except ProtectedError as e:
            request.session['message_class'] = "alert alert-danger"
            messages.error(request, "Error de integridad: La jefatura esta asociada a un proceso por lo cual no puede ser eliminada .")
            return HttpResponseRedirect('/controlador/listar')

        except Exception  as e:
            request.session['message_class'] = "alert alert-danger"
            messages.error(request, "Error interno: No se ha eliminado el registro. Comuníquese con el administrador.")
            return HttpResponseRedirect('/controlador/listar')




########################################################################################################################
########################################################################################################################
########################################################################################################################


class ControladorUpdate(UpdateView):
    model = Ges_Controlador
    form_class = GestionControladorUpdateForm
    template_name = 'controlador/actividades_enviar.html'

    def get_form_kwargs(self, **kwargs):
        kwargs = super(ControladorUpdate, self).get_form_kwargs()
        id_usuario_actual = self.request.user.id
        try:
            periodo_actual = Glo_Periodos.objects.get(id_estado=1)
        except Glo_Periodos.DoesNotExist:
            return None
        try:
            nivel_usuario = Ges_Jefatura.objects.get(Q(id_user=id_usuario_actual) & Q(id_periodo=periodo_actual.id))

        except Ges_Jefatura.DoesNotExist:
            return None

        id_nivel = nivel_usuario.id_nivel.id
        replies = Ges_Niveles.objects.filter(Q(id=id_nivel) & Q(id_periodo=periodo_actual.id)).annotate(
            nivel_order=Case(
                When(orden_nivel=1, then='id_primer_nivel'),
                When(orden_nivel=2, then='id_segundo_nivel'),
                When(orden_nivel=3, then='id_tercer_nivel'),
                When(orden_nivel=4, then='id_cuarto_nivel'),
                output_field=CharField(),
            )
        )
        for nivel in replies:
            id_nivel_final = nivel.nivel_order
            id_orden = nivel.orden_nivel


        if id_orden == 2:
            id_primerNivel = Ges_SegundoNivel.objects.get(id=id_nivel_final)
        if id_orden == 3:
            id_SegundoNivel = Ges_TercerNivel.objects.get(id=id_nivel_final)
        if id_orden == 4:
            id_tercerNivel = Ges_CuartoNivel.objects.get(id=id_nivel_final)

        if id_orden == 2:
            id_nivel_jefsuperior = Ges_Niveles.objects.get(id_primer_nivel=id_primerNivel.primer_nivel_id)
        if id_orden == 3:
            id_nivel_jefsuperior = Ges_Niveles.objects.get(id_segundo_nivel=id_SegundoNivel.segundo_nivel_id)
        if id_orden == 4:
            id_nivel_jefsuperior = Ges_Niveles.objects.get(id_tercer_nivel=id_tercerNivel.tercer_nivel_id)

        try:
            id_jef_final = Ges_Jefatura.objects.get(
                id_nivel=id_nivel_jefsuperior.id)  # SI NO ENCUENTRA UN JEFE SE CAE, VALIDAR
        except Ges_Jefatura.DoesNotExist:
            id_jef_final = 0
            pass

        if id_jef_final != 0:
            id_jef_final = int(id_jef_final.id_nivel_id)
            kwargs['nivel_jefatura'] = id_jef_final
            return kwargs
        else:

            kwargs['nivel_jefatura'] = id_jef_final
            return kwargs

    def post(self, request, *args, **kwargs):
        self.object = self.get_object
        id_nivel = kwargs['pk']
        id_nivel = int(id_nivel)
        instancia_nivel = self.model.objects.get(id=id_nivel)
        id_jefatura = request.POST['jefatura_primerarevision']
        id_jefatura_solicita = request.POST['id_jefatura']
        id_usuario_actual = self.request.user.id
        id_nivel_post = Ges_Jefatura.objects.get(id=id_jefatura)
        id_nivel_post = id_nivel_post.id_nivel_id
        form = self.form_class(id_nivel_post, request.POST, instance=instancia_nivel)

        try:
            periodo_actual = Glo_Periodos.objects.get(id_estado=1)
        except Glo_Periodos.DoesNotExist:
            return None

        nivel_usuario = Ges_Jefatura.objects.get(Q(id_user=id_usuario_actual) & Q(id_periodo=periodo_actual.id))
        idcorreoJefaturaOb =   Ges_Jefatura.objects.get(id=id_jefatura)
        Actividades = Ges_Actividad.objects.filter(Q(id_periodo=periodo_actual.id) & Q(
            id_controlador=instancia_nivel.id)).count()


        count_obs_no_vistas = Ges_Observaciones.objects.filter(
            Q(id_controlador=id_nivel) & Q(observado=1) & ~Q(user_observa_id=id_usuario_actual)).count()
        count_obs_no_vistas_generales = Ges_Observaciones_sr.objects.filter(
            Q(id_controlador=id_nivel) & Q(observado=1) & ~Q(user_observa_id=id_usuario_actual)).count()

        if count_obs_no_vistas == 0 and count_obs_no_vistas_generales == 0:
            if Actividades != 0:

                if form.is_valid():
                    form.save()


templates/controlador/actividades_enviar.html
			<header class="panel-heading">
				<div class="panel-actions">
				<a class="fa fa-times" data-dismiss="modal"></a>
				</div>
				<h2 class="panel-title">Solicitud Revisión</h2>
			</header>

			<form  method="post"  action="" >

				<div class="panel-body">
					{% csrf_token %}

					 <div class="{% if form.non_field_errors %}invalid{% endif %} mb-2">
    					  {% for error in form.non_field_errors %}
        					{{ error }}
     					 {% endfor %}
    				</div>

<div class="row show-grid">

                    <div class="col-md-12">
                        <span class="show-grid-block">

                           <div class="form-group">
					<label >Jefatura solicitante</label>
					{{ form.id_jefatura}}
				</div>
                            <div class="form-group">
					<label >Estado flujo</label>
					{{ form.estado_flujo}}
				</div>

                  <div id="select_jefatura" class="form-group">
					<label >Jefatura revisión</label>
					{{ form.jefatura_primerarevision}}
				</div>






                   </span>

                    </div>

     </div>
					<BR>
	<div id="display_confirmar"  class="alert alert-warning" role="alert">
  Al presionar "confirmar" su plan de trabajo será enviado a la jefatura seleccionada.
</div>

		<div id="display_error" style="display:none;" class="alert alert-danger" role="alert">
            Su jefatura superior no ha sido cargada, contáctese con el área de Planificación.
        </div>

</div>
			</div>
			<div class="modal-footer">



			<div id="enviar" style="display:none; text-align:left; " class="alert alert-info" role="alert">
            Enviando correos, favor espere...
       		 </div>



				<button class="btn btn-danger" type="submit" id="confirmar" >Confirmar</button>
				<button class="btn btn-default" type="button"  id="cancelar" data-dismiss="modal">Cancelar</button>
			</div>

								<div class="alert alert-danger" style="display:none;" id="mjeError">
									<p id="textError"></p>
								</div>
			</form>

			<script>
   // Shorthand for $( document ).ready()
    $(function() {
       $('#id_id_jefatura option:not(:selected)').attr('disabled',true);
        $('#id_estado_flujo option:not(:selected)').attr('disabled',true);

    //});



    var select_primera = $("#id_jefatura_primerarevision option:last").val();


    //alert(select_segunda2);

    if (select_primera == '') {

    $('#display_error').css('display','block');
    $('#select_jefatura').css('display','none');
    $('#display_confirmar').css('display','none');
    $('#confirmar').css('display','none');
		}

    });


$('#confirmar').click(function() {
var select_primera = $("#id_jefatura_primerarevision").val();

if (select_primera != '') {
     $( this ).hide();
     $( '#display_confirmar' ).hide();
     $( '#cancelar' ).hide();
      $( '#enviar' ).fadeIn();
}
});


			</script>

templates/controlador/controlador_delete.html
		<header class="panel-heading">
				<div class="panel-actions">
				<a class="fa fa-times" data-dismiss="modal"></a>
				</div>
				<h2 class="panel-title">Eliminar Jefaturas</h2>
			</header>
<form method="post" action="">
  {% csrf_token %}


    <div class="panel-body">
    <div class="modal-wrapper">
        <div class="modal-icon">
            <i class="fa fa-warning"></i>
                </div>
            <div class="modal-text">
                <h4>Atención</h4>
                <p>¿Está seguro de eliminar el registro?. Recuerde que una vez borrado no se podrá recuperar. </p>



            </div>
        </div>
    </div>

  <div class="modal-footer">
    <button class="btn btn-danger" type="submit" >Eliminar</button>
     <button class="btn btn-default" type="button" data-dismiss="modal">Cancelar</button>
  </div>

</form>

templates/controlador/controlador_form.html

	<header class="panel-heading">
				<div class="panel-actions">
				<a class="fa fa-times" data-dismiss="modal"></a>
				</div>
				<h2 class="panel-title">Registro Áreas que Ingresan Actividades</h2>
			</header>

			<form  method="post"  action="" >

				<div class="panel-body">
					{% csrf_token %}

					 <div class="{% if form.non_field_errors %}invalid{% endif %} mb-2">
    					  {% for error in form.non_field_errors %}
        					{{ error }}
     					 {% endfor %}
    				</div>


				<div class="col-md-12">

                    <div class="form-group">
					<label >Área que ingresa actividades</label>
					{{ form.id_jefatura }}
				    </div>

				</div>

			</div>

			<div class="modal-footer">
				<button class="btn btn-primary" type="submit" id="confirmar"  >Confirmar</button>
				<button class="btn btn-default" type="button" data-dismiss="modal">Cancelar</button>
			</div>

			</form>
	<script>


$(function() {
       $('#siteID').select2({
        dropdownParent: $('#modalCreate')
    });

});
</script>

templates/controlador/controlador_list.html
{% extends 'base/base.html' %}
{% block title %}
Gestionar las Jefaturas que Elaboran Planes de Gestión
{% endblock %}
{% block content %}

{% if messages %}
		  {% for message in messages %}

			<div style="border-radius:0;" {% if message.tags %} id="danger-alert" class="{{request.session.message_class}} fade show mb-0" role="alert" {% endif %}>
			  {{ message }}
			  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
				<span aria-hidden="true">&times;</span>
			  </button>
			</div>

		  {% endfor %}

	{% endif %}

	<section class="panel">
							<header class="panel-heading">
								<div class="panel-actions">



								 <button  type="button" class="create btn btn-sm btn-success"  name="button" title="Agregar Nivel">
      								<span class="fa fa-plus"></span></button>


									<!--<a href="#" class="fa fa-times"></a>-->
								</div>


								<h2 class="panel-title">  Jefaturas que Elaboran Planes de Gestión </h2>

							</header>
							<div class="panel-body">
								<table class="table table-bordered table-striped mb-none" id="datatable-default">
									<thead>
										<tr>
                                            <th>Nivel</th>
                                            <th>Jefatura</th>
											<th>Periodo</th>


<!--                                            <th>Nivel Inicial</th>-->
<!--                                             <th>Fecha Última Modificación</th>-->
                                            <th>Estado Flujo</th>
                                            <th>Opciones</th>
										</tr>
									</thead>
									<tbody>

                                            {% for controlador in object_list %}
                                                <tr>
 													<td> {{ controlador.id_jefatura.id_nivel }} </td>
                                                    <td> {{ controlador.id_jefatura.id_user }} </td>
                                                    <td> {{ controlador.id_periodo }} </td>

<!--                                                    <td> {{ controlador.nivel_inicial }} </td>-->
<!--                                                    <td> {{ controlador.fecha_ultima_modificacion }} </td>-->
                                                     <td> {{ controlador.estado_flujo }} </td>

    												 <td style="width:80px; text-align:center;">
<!--														 <button type="button" title="Actualizar Registro" class="update btn btn-sm btn-primary" data-id="{% url 'producto_editar' controlador.id %}" >-->
<!--														<span class="fa fa-pencil"></span></button>-->
														 <button type="button" title="Eliminar Registro" class="delete btn btn-sm btn-danger" data-id="{% url 'controlador_delete' controlador.id %}">
      													  <span class="fa fa-trash-o"></span></button>


                                                    </td>
                                                </tr>
                                            {% endfor %}


									</tbody>
								</table>

							</div>
						</section>




<!--Cabecera del modal -->
<div class="modal fade" tabindex="-1" role="dialog" id="modalCreate">
  <div class="modal-dialog modal-md" role="document">
	<div class="modal-content">

    </div>
  </div>
</div>

	<div class="modal fade" tabindex="-1" role="dialog" id="modalDetalle">
  <div class="modal-dialog modal-xs" role="document">
	<div class="modal-content">

    </div>
  </div>

</div>
<div class="modal fade" tabindex="-1" role="dialog" id="modalUpdate">
  <div class="modal-dialog modal-lg" role="document">
	<div class="modal-content">

    </div>
  </div>
</div>


<div class="modal fade" tabindex="-1" role="dialog" id="modalDelete">
  <div class="modal-dialog modal-xs" role="document">
	<div class="modal-content">

    </div>
  </div>
</div>
<!--Fin cabecera del modal -->



	{% block extrajs %}



<script type="text/javascript">

	// JS modal crea Registro
  	 $(".create").modalForm(  {formURL: "{% url 'controlador_crear' %}", modalID: $("#modalCreate")});


   	 // JS modal actualiza Registro
   $(".update").each(function () {
   $(this).modalForm({formURL: $(this).data('id'),  modalID: $("#modalUpdate")});

    });


    // JS modal elimina Registro
    $(".delete").each(function () {
    $(this).modalForm({formURL: $(this).data('id'),  modalID: $("#modalDelete")});
	});


     // Js Muestra/Oculta Mensaje Success
   	 $(".alert").fadeTo(10000, 500).slideUp( "slow", function() {
     $(this).remove();
  });



</script>


		{% endblock %}



{% endblock %}