apps/periodos/urls.py
from django.urls import path
from django.conf.urls import url
from . import views
from django.contrib.auth.decorators import login_required

urlpatterns = [

    path('listar', login_required(views.PeriodosList.as_view()), name='periodos_listar'),
    path('create', login_required(views.PeriodosCreate.as_view()), name='periodos_crear'),
    path('edit/<int:pk>', login_required(views.PeriodosEdit.as_view()), name='periodo_editar'),
    path('delete/<int:pk>', login_required(views.PeriodosDelete.as_view()), name='periodo_delete'),

    path('listar_seguimiento/<int:pk>', login_required(views.SeguimientoList.as_view()), name='seguimiento_listar'),
    path('seguimiento_cerrar/<int:pk>', login_required(views.SeguimientoCerrarPeriodo.as_view()), name='seguimiento_cerrar'),
    path('seguimiento_abrir_periodo', login_required(views.SeguimientoAbrirPeriodo.as_view()), name='seguimiento_abrir'),

    path('listar_validacion/<int:pk>', login_required(views.ValidacionList.as_view()), name='validacion_listar'),
    path('validacion_abrir_periodo', login_required(views.ValidacionAbrirPeriodo.as_view()), name='validacion_abrir'),
    path('validacion_cerrar/<int:pk>', login_required(views.ValidacionCerrarPeriodo.as_view()), name='validacion_cerrar'),
]

proyecto_django/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [

    path(r'periodos/', include('apps.periodos.urls')),


    path(r'accounts/', include('apps.registration.urls')),
    path(r'admin/', admin.site.urls),
    path(r'dashboard/', include('apps.dashboard.urls')),
    path(r'estructura/', include('apps.estructura.urls')),
    path(r'objetivos/', include('apps.objetivos.urls')),
    path(r'horas/', include('apps.gestion_horas.urls')),
    path(r'jefaturas/', include('apps.jefaturas.urls')),
    path(r'feriados/', include('apps.feriados.urls')),
    path(r'ejes/', include('apps.eje.urls')),
    path(r'vista_objetivos/', include('apps.vista_objetivos.urls')),
    path(r'familiadecargos/', include('apps.familia_cargo.urls')),

    path(r'periodicidad/', include('apps.periodicidad.urls')),
    path(r'productos/', include('apps.productos.urls')),
    path(r'estado_flujo/', include('apps.estado_flujo.urls')),
    path(r'controlador/', include('apps.controlador.urls')),
    path(r'actividades/', include('apps.actividades.urls')),
    path(r'valida_plan/', include('apps.valida_plan.urls')),
    path(r'valida_plan2/', include('apps.valida_plan2.urls')),
    path(r'perfiles/', include('apps.perfiles.urls')),

    path(r'revision_planificacion/', include('apps.revision_planificacion.urls')),
    path(r'seguimiento_formula/', include('apps.seguimiento_formula.urls')),
    path(r'reportes/', include('apps.reportes.urls')),
    path(r'valida_seguimiento/', include('apps.valida_seguimiento.urls')),
    path(r'planificacion_admin/', include('apps.planificacion_admin.urls')),





]





apps/periodos/models.py
from django.db import models
from apps.estado_seguimiento.models import Glo_EstadoSeguimiento
# Create your models here.

# Create your models here.
class Glo_EstadoPeriodo(models.Model):
    estado= models.IntegerField()
    descripcion_periodo= models.CharField(max_length=100)

    def __str__(self):
        return '{}'.format(self.descripcion_periodo)


class Glo_Periodos(models.Model):
    descripcion_periodo = models.CharField(max_length=100)
    anio_periodo= models.IntegerField()
    fecha_inicio=models.DateField(blank=True, null=True)
    fecha_termino=models.DateField(blank=True, null=True)
    id_estado = models.ForeignKey(Glo_EstadoPeriodo, on_delete=models.PROTECT, null=True)


    def __str__(self):
        return '{}'.format(self.descripcion_periodo)



class Glo_Seguimiento(models.Model):
    id_periodo= models.ForeignKey(Glo_Periodos, on_delete=models.PROTECT, null=True, blank=True)
    fecha_inicio= models.DateTimeField(blank=True, null=True)
    fecha_termino= models.DateTimeField(blank=True, null=True)
    descripcion_seguimiento = models.CharField(max_length=100, null=True, blank=True)
    fecha_inicio_corte=models.DateField(blank=True, null=True)
    fecha_termino_corte=models.DateField(blank=True, null=True)

    id_estado_seguimiento= models.ForeignKey(Glo_EstadoSeguimiento, on_delete=models.PROTECT, null=True, blank=True)

    def __str__(self):
        return '{}'.format(self.descripcion_seguimiento)

class Glo_validacion(models.Model):
    id_periodo= models.ForeignKey(Glo_Periodos, on_delete=models.PROTECT, null=True, blank=True)
    id_periodo_seguimiento = models.ForeignKey(Glo_Seguimiento, on_delete=models.PROTECT, null=True, blank=True)
    fecha_inicio= models.DateTimeField(blank=True, null=True)
    fecha_termino= models.DateTimeField(blank=True, null=True)
    id_estado_periodo= models.ForeignKey(Glo_EstadoSeguimiento, on_delete=models.PROTECT, null=True, blank=True)
    descripcion_validacion = models.CharField(max_length=100, null=True, blank=True)

apps/periodos/forms.py
from django import forms
from apps.periodos.models import Glo_Periodos, Glo_Seguimiento, Glo_validacion

class DateInput(forms.DateInput):
    input_type = 'date'



class periodosForm(forms.ModelForm):
    ANIO_CHOICES = (
        (2020, '2020'),
        (2021, '2021'),
        (2022, '2022'),
        (2023, '2023'),
        (2024, '2024'),
        (2025, '2025')
    )

    TRUE_FALSE_CHOICES = (
        (True, 'Activo'),
        (False, 'Inactivo')

    )

    anio_periodo = forms.ChoiceField(choices=ANIO_CHOICES,
                                   widget=forms.Select(attrs={'class': 'form-control'}))


    estado = forms.ChoiceField(choices=TRUE_FALSE_CHOICES,
                                   widget=forms.Select(attrs={'class': 'form-control'}))

    class Meta:
        model = Glo_Periodos

        fields = [
            'descripcion_periodo',
            'anio_periodo',
            'estado',

        ]


        widgets = {

            'descripcion_periodo': forms.TextInput(attrs={'class': 'form-control'}),

        }

class Seguimiento_cierreform(forms.ModelForm):


    class Meta:
        model = Glo_Seguimiento
        fields = [
            'fecha_termino',

        ]


class Seguimiento_abrirform(forms.ModelForm):


    class Meta:
        model = Glo_Seguimiento
        fields = [
            'descripcion_seguimiento',
            'fecha_termino',
            'fecha_inicio_corte',
            'fecha_termino_corte',
        ]

        widgets = {
            'descripcion_seguimiento': forms.TextInput(attrs={'class': 'form-control'}),
            'fecha_inicio_corte': DateInput(attrs={'class': 'form-control', 'required':'required', 'id':'id_fecha_inicio_corte'}),
            'fecha_termino_corte': DateInput(attrs={'class': 'form-control', 'required':'required', 'id':'id_fecha_termino_corte'}),

        }

class validacion_abrirform(forms.ModelForm):


    class Meta:
        model = Glo_validacion
        fields = [
            'descripcion_validacion',
            'fecha_termino',
            'id_periodo_seguimiento',

        ]

        widgets = {
            'descripcion_validacion': forms.TextInput(attrs={'class': 'form-control', 'required':'required'}),
            'fecha_termino': DateInput(
                attrs={'class': 'form-control', 'required': 'required'}),
            'id_periodo_seguimiento': forms.Select(attrs={'class': 'form-control', 'required':'required'}),

        }
class valida_cierreform(forms.ModelForm):


    class Meta:
        model = Glo_validacion
        fields = [
       #     'fecha_termino',

        ]

apps/periodos/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from apps.periodos.forms import periodosForm, Seguimiento_cierreform, Seguimiento_abrirform, validacion_abrirform, valida_cierreform
from apps.periodos.models import Glo_Periodos, Glo_Seguimiento, Glo_validacion
from apps.controlador.models import Ges_Controlador
from apps.jefaturas.models import Ges_Jefatura
from apps.estado_seguimiento.models import Glo_EstadoSeguimiento

from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from django.http import HttpResponseRedirect
from django.db.models.deletion import ProtectedError
from django.core.mail import EmailMessage,send_mass_mail

from django.db.models import Q
from datetime import date
from datetime import datetime
from django.utils import timezone
# Create your views here.


class PeriodosList(ListView):
    model = Glo_Periodos
    template_name = 'periodos/periodo_list.html'


class PeriodosCreate(SuccessMessageMixin, CreateView):
    model = Glo_Periodos
    form_class = periodosForm
    template_name = 'periodos/periodo_form.html'


    def post(self, request, *args, **kwargs):
        form_class = self.get_form_class()
        form = self.get_form(form_class)

        if form.is_valid():
            form.instance.fecha_inicio= date.today()
            form.save()
            request.session['message_class'] = "alert alert-success"
            messages.success(self.request, "Los datos fueron creados correctamente!")
            return HttpResponseRedirect('/periodos/listar')
        else:
            request.session['message_class'] = "alert alert-danger"
            messages.error(self.request, "Error interno: No se ha creado el registro. Comuníquese con el administrador.")
            return HttpResponseRedirect('/periodos/listar')



class PeriodosEdit(SuccessMessageMixin, UpdateView ):
    model = Glo_Periodos
    form_class = periodosForm
    template_name = 'periodos/periodo_form.html'

    def post(self, request, *args, **kwargs):

        self.object = self.get_object
        id_periodo = kwargs['pk']
        instancia_nivel = self.model.objects.get(id=id_periodo)
        form = self.form_class(request.POST, instance=instancia_nivel)

        if form.is_valid():
            form.save()
            request.session['message_class'] = "alert alert-success"
            messages.success(self.request, "Los datos fueron actualizados correctamente!" )
            return HttpResponseRedirect('/periodos/listar')
        else:
            request.session['message_class'] = "alert alert-danger"
            messages.error(self.request, "Error interno: No se ha actualizado el registro. Comuníquese con el administrador.")
            return HttpResponseRedirect('/periodos/listar')


class PeriodosDelete(SuccessMessageMixin, DeleteView ):
    model = Glo_Periodos
    template_name = 'periodos/periodo_delete.html'

    def delete(self, request, *args, **kwargs):
        obj = self.get_object()
        try:
            obj.delete()
            request.session['message_class'] = "alert alert-success"
            messages.success(self.request, "El registro fue eliminado correctamente!")
            return HttpResponseRedirect('/periodos/listar')

        except ProtectedError as e:
            request.session['message_class'] = "alert alert-danger"
            messages.error(request, "Error de integridad: Este nivel posee subniveles los que deben ser borrados antes de borrar este nivel.")
            return HttpResponseRedirect('/periodos/listar')

        except Exception  as e:
            request.session['message_class'] = "alert alert-danger"
            messages.error(request, "Error interno: No se ha eliminado el registro. Comuníquese con el administrador.")
            return HttpResponseRedirect('/periodos/listar')




class SeguimientoList(ListView):
    model = Glo_Seguimiento
    template_name = 'periodos/seguimiento_list.html'



    def get_context_data(self, **kwargs):
        context = super(SeguimientoList, self).get_context_data(**kwargs)
        #id_usuario_actual = self.request.user.id  # obtiene id usuario actual
        self.request.session['id_periodo']=self.kwargs['pk'] #guarda id  controlador


        queryset= Glo_Seguimiento.objects.filter(id_periodo=self.kwargs['pk'])


        context['object_list'] = queryset
        context['periodo'] = PeriodoActual()




        return context


class SeguimientoCerrarPeriodo(UpdateView):
    model = Glo_Seguimiento
    template_name = 'periodos/seguimiento_cerrar.html'
    form_class = Seguimiento_cierreform

    def post(self, request, *args, **kwargs):
        self.object = self.get_object
        pk = kwargs['pk']
        instancia = self.model.objects.get(id=pk)
        form = self.form_class(request.POST, instance=instancia)

        id_nuevo_estado= Glo_EstadoSeguimiento.objects.get(id=2)

        id_periodo=self.request.session['id_periodo']

        if form.is_valid():

            form.instance.id_estado_seguimiento=id_nuevo_estado
            form.instance.fecha_termino= datetime.now(tz=timezone.utc)

            form.save()

            try:

                EnviarCorreoCierreSeguimiento()

                request.session['message_class'] = "alert alert-success"  # Tipo mensaje
                messages.success(request, "La etapa de seguimiento fue cerrada y se le ha enviado un correo a las jefaturas que formulan.!")  # mensaje
                return HttpResponseRedirect('/periodos/listar_seguimiento/' + str(id_periodo))  # Redirije a la pantalla principal

            except:

                 request.session['message_class'] = "alert alert-warning" #Tipo mensaje
                 messages.success(request, "La etapa de seguimiento fue cerrada correctamente!, pero el servicio de correo tuvo un inconveniente favor comuníquese con las jefaturas que formulan para informar el cierre de esta etapa.") # mensaje
                 return HttpResponseRedirect('/periodos/listar_seguimiento/' + str(id_periodo)) # Redirije a la pantalla principal

        else:

            request.session['message_class'] = "alert alert-danger"
            messages.error(self.request, "Error interno: No se ha cerrado la etapa de seguimiento. Comuníquese con el administrador.")
            return HttpResponseRedirect('/periodos/listar_seguimiento' + str(id_periodo))



class SeguimientoAbrirPeriodo(SuccessMessageMixin, CreateView):
    model = Glo_Seguimiento
    template_name = 'periodos/seguimiento_abrir.html'
    form_class = Seguimiento_abrirform


    def get_context_data(self, **kwargs):
        context = super(SeguimientoAbrirPeriodo, self).get_context_data(**kwargs)

        try:
             estado= Glo_Seguimiento.objects.get(Q(id_estado_seguimiento=1) & Q(id_periodo=PeriodoActual()))
        except Glo_Seguimiento.DoesNotExist:
             estado = 0

        try:
             estadoValida= Glo_validacion.objects.get(Q(id_estado_periodo=1) & Q(id_periodo=PeriodoActual()))
        except Glo_validacion.DoesNotExist:
             estadoValida = 0

        try:
            planes_no_aprobados= Ges_Controlador.objects.filter(Q(id_periodo=PeriodoActual()) & (~Q(estado_flujo_id=7) & ~Q(estado_flujo_id=2))).count()
        except Ges_Controlador.DoesNotExist:
            planes_no_aprobados = 0

        context["estado_seguimiento"] = {'estadoValida': estadoValida, 'estado_seguimiento': estado, 'planes_no_aprobados':planes_no_aprobados}
        return context

    def post(self, request, *args, **kwargs):
        form_class = self.get_form_class()
        form = self.get_form(form_class)


        id_nuevo_estado= Glo_EstadoSeguimiento.objects.get(id=1)
        periodo_actual = Glo_Periodos.objects.get(id_estado=1)

        id_periodo=self.request.session['id_periodo']

        if form.is_valid():
            form.instance.id_periodo= periodo_actual
            form.instance.id_estado_seguimiento=id_nuevo_estado
            form.instance.fecha_inicio= datetime.now(tz=timezone.utc)

            form.save()

            try:
                Ges_Controlador.objects.filter(id_periodo=PeriodoActual()).update(id_estado_plan=1)
                EnviarCorreoAbrirSeguimiento()

                request.session['message_class'] = "alert alert-success"  # Tipo mensaje
                messages.success(request, "El periodo de seguimiento fue abierto correctamente! y se ha enviado un correo a las jefaturas que formulan!")  # mensaje
                return HttpResponseRedirect('/periodos/listar_seguimiento/' + str(id_periodo))  # Redirije a la pantalla principal

            except:

                 request.session['message_class'] = "alert alert-warning" #Tipo mensaje
                 messages.success(request, "El periodo de seguimiento fue abierto correctamente!, pero el servicio de correo tuvo un inconveniente favor comuníquese con la jefatura directa para informar de la apertura.") # mensaje
                 return HttpResponseRedirect('/periodos/listar_seguimiento/' + str(id_periodo)) # Redirije a la pantalla principal

        else:

            request.session['message_class'] = "alert alert-danger"
            messages.error(self.request, "Error interno: No se ha abierto la etapa de seguimiento. Comuníquese con el administrador.")
            return HttpResponseRedirect('/periodos/listar_seguimiento/' + str(id_periodo))

class ValidacionCerrarPeriodo(UpdateView):
    model = Glo_validacion
    template_name = 'periodos/validacion_cerrar.html'
    form_class = valida_cierreform

    def post(self, request, *args, **kwargs):
        self.object = self.get_object
        pk = kwargs['pk']

templates/periodos/periodo_delete.html
		<header class="panel-heading">
				<div class="panel-actions">
				<a class="fa fa-times" data-dismiss="modal"></a>
				</div>
				<h2 class="panel-title">Cerrar Periodo</h2>
			</header>
<form method="post" action="">
  {% csrf_token %}


    <div class="panel-body">
    <div class="modal-wrapper">
        <div class="modal-icon">
            <i class="fa fa-warning"></i>
                </div>
            <div class="modal-text">
                <h4>Cerrar Periodo</h4>
                <p> </p>



            </div>
        </div>
    </div>

  <div class="modal-footer">
    <button class="btn btn-danger" type="submit" >Eliminar</button>
     <button class="btn btn-default" type="button" data-dismiss="modal">Cancelar</button>
  </div>

</form>

templates/periodos/periodo_form.html

	<header class="panel-heading">
				<div class="panel-actions">
				<a class="fa fa-times" data-dismiss="modal"></a>
				</div>
				<h2 class="panel-title">Registro Periodos</h2>
			</header>

			<form  method="post"  action="" >

				<div class="panel-body">
					{% csrf_token %}

					 <div class="{% if form.non_field_errors %}invalid{% endif %} mb-2">
    					  {% for error in form.non_field_errors %}
        					{{ error }}
     					 {% endfor %}
    				</div>


				<div class="col-md-6">
					<div  class="form-group">
					<label >Año</label>
					{{ form.anio_periodo }}
				    </div>

                    <div class="form-group">
					<label >Descripción Periodo</label>
					{{ form.descripcion_periodo }}
				    </div>


                    <div class="form-group" style="display:none;">
					<label >Estado Periodo</label>
					{{ form.estado }}
				    </div>




				</div>

			</div>

			<div class="modal-footer">
				<button class="btn btn-primary" type="submit" id="confirmar"  >Confirmar</button>
				<button class="btn btn-default" type="button" data-dismiss="modal">Cancelar</button>
			</div>

			</form>





templates/periodos/periodo_list.html
{% extends 'base/base.html' %}

{% block content %}

{% if messages %}
		  {% for message in messages %}

			<div style="border-radius:0;" {% if message.tags %} id="danger-alert" class="{{request.session.message_class}} fade show mb-0" role="alert" {% endif %}>
			  {{ message }}
			  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
				<span aria-hidden="true">&times;</span>
			  </button>
			</div>

		  {% endfor %}

	{% endif %}

	<section class="panel">
							<header class="panel-heading">
								<div class="panel-actions">



								 <button  type="button" class="create btn btn-sm btn-success"  name="button" title="Agregar Periodo">
      								<span class="fa fa-plus"></span></button>


									<!--<a href="#" class="fa fa-times"></a>-->
								</div>


								<h2 class="panel-title">  Listado de Periodos  </h2>

							</header>
							<div class="panel-body">
								<table class="table table-bordered table-striped mb-none" id="datatable-default">
									<thead>
										<tr>

											<th>Descripción Periodo</th>
											<th>Año</th>
                                            <th>Estado</th>
                                            <th>Opciones</th>
										</tr>
									</thead>
									<tbody>

                                            {% for periodo in object_list %}
                                                <tr>

                                                    <td> {{ periodo.descripcion_periodo }} </td>

													<td> {{ periodo.anio_periodo}}</td>

                                                    <td  {% if periodo.id_estado.id == 1  %}
														 style="color:#47a447; width:130px; font-weight: bold;"
														 {% elif periodo.id_estado.id == 2  %}
														 style="color:#919191; width:130px; font-weight: bold;"
														 {% elif periodo.id_estado.id == 3  %}
														 style="color:red; width:130px; font-weight: bold;"
														 {%endif%} > {{ periodo.id_estado }} </td>


    												 <td style="width:120px; text-align:center;">
<!--														{% if periodo.id_estado.id == 1  %}  <button type="button" title="Actualizar Registro" class="update btn btn-sm btn-primary" data-id="{% url 'periodo_editar' periodo.id %}" >-->
<!--														<span class="fa fa-pencil"></span></button>{%endif%}-->
<!--														 <button type="button" title="Eliminar Registro" class="delete btn btn-sm btn-danger" data-id="{% url 'periodo_delete' periodo.id %}">-->
<!--      													  <span class="fa fa-trash-o"></span></button>-->
														 {% if periodo.id_estado.id == 1  %}  <button type="button" title="Cerrar Periodo" class="delete btn btn-sm btn-danger" data-id="{% url 'periodo_delete' periodo.id %}">
      													  <span class="fa fa-lock"></span></button>{%endif%}
														 {% if periodo.id_estado.id == 1  %} <a type="button"  data-toggle="tooltip" data-original-title="Tooltip on bottom" data-placement="top" title="Administrar Periodos de Seguimiento" class="objetivo btn btn-sm btn-success" href="{% url 'seguimiento_listar' periodo.id %}">
      													  <span class="fa fa-flag-checkered"></span></a>{%endif%}
															{% if periodo.id_estado.id == 1  %} <a type="button"  data-toggle="tooltip" data-original-title="Tooltip on bottom" data-placement="top" title="Administrar Periodos de Validación" class="objetivo btn btn-sm btn-success" href="{% url 'validacion_listar' periodo.id %}">
      													  <span class="fa fa-check-square-o"></span></a>{%endif%}
                                                    </td>
                                                </tr>
                                            {% endfor %}


									</tbody>
								</table>

							</div>
						</section>




<!--Cabecera del modal -->
<div class="modal fade" tabindex="-1" role="dialog" id="modalCreate">
  <div class="modal-dialog modal-lg" role="document">
	<div class="modal-content">

    </div>
  </div>
</div>

	<div class="modal fade" tabindex="-1" role="dialog" id="modalDetalle">
  <div class="modal-dialog modal-xs" role="document">
	<div class="modal-content">

    </div>
  </div>

</div>
<div class="modal fade" tabindex="-1" role="dialog" id="modalUpdate">
  <div class="modal-dialog modal-lg" role="document">
	<div class="modal-content">

    </div>
  </div>
</div>


<div class="modal fade" tabindex="-1" role="dialog" id="modalDelete">
  <div class="modal-dialog modal-xs" role="document">
	<div class="modal-content">

    </div>
  </div>
</div>
<!--Fin cabecera del modal -->



	{% block extrajs %}



<script type="text/javascript">

	// JS modal crea Registro
  	 $(".create").modalForm(  {formURL: "{% url 'periodos_crear' %}", modalID: $("#modalCreate")});


   	 // JS modal actualiza Registro
   $(".update").each(function () {
   $(this).modalForm({formURL: $(this).data('id'),  modalID: $("#modalUpdate")});

    });


    // JS modal elimina Registro
    $(".delete").each(function () {
    $(this).modalForm({formURL: $(this).data('id'),  modalID: $("#modalDelete")});
	});


     // Js Muestra/Oculta Mensaje Success
   	 $(".alert").fadeTo(5000, 500).slideUp( "slow", function() {
     $(this).remove();
  });

	$('#datatable-default').DataTable({
	"order": [[ 2, "asc" ]] //desactiva el ordenamiento de la tabla para que el order_by del queryset funcione. ("order": [[ 3, "desc" ]]) para ordenar desde jquery.
	});


</script>


		{% endblock %}



{% endblock %}

templates/periodos/validacion_abrir.html
<header class="panel-heading">

        <h2 class="panel-title">Apertura Periodo Validación</h2>
</header>

<form method="post" action="">
    {% csrf_token %}
{%if estado_seguimiento.estadoValida != 0 or estado_seguimiento.estado_seguimiento != 0 %}


<div class="panel-body">
    <div class="modal-wrapper">
        <div class="modal-icon">
            <i class="fa fa-warning"></i>
        </div>
            <div class="modal-text">
                <h4>Atención</h4>
                <p>Estimado Usuario, para abrir un nuevo periodo debe <b>cerrar</b> el proceso que se encuentra abierto.</p>

            </div>
    </div>


  <div class="modal-footer">

     <button class="btn btn-default" type="button" data-dismiss="modal">Cerrar</button>
  </div>

</div>
{%else %}



    <div class="panel-body">
    <div class="modal-wrapper">

		<div class="col-md-12">
                	<div  class="form-group">
              <label >Descripción Periodo </label>

					{{form.descripcion_validacion}}

                    </div>


					<div  class="form-group">
              <label >Fecha Término </label>
				<div class="input-group">
				<span class="input-group-addon">
					<i class="fa fa-calendar"></i>
				</span>
					{{form.fecha_termino}}
				</div>
                    </div>
            	<div  class="form-group">
              <label >Periodo Seguimiento  </label>


					{{form.id_periodo_seguimiento}}

                    </div>

<br>

 <div class="modal-text">

                <h4 style="color:red;">¡Atención!</h4>
                <p style="color:red;">¿Está seguro que desea abrir un nuevo periodo de validación? </p>

  </div>
    </div>
</div>



        </div>
  <div class="modal-footer">
           <div id="enviar" style="display:none; text-align:left; " class="alert alert-info" role="alert">
            Enviando correos, favor espere...
            </div>


      								<div class="alert alert-danger" style="display:none;" id="mjeError">
									<p id="textError"></p>
								</div>

     <button class="btn btn-danger" type="submit" id="confirmar"  >Abrir Periodo Validación</button>
     <button class="btn btn-default" type="button" id="cancelar"  data-dismiss="modal">Cerrar</button>
  </div>




{%endif %}

</form>


<script>



 $('#confirmar').click(function() {
    var fecha_actual= moment();
    var fecha_termino='';
   var fecha_termino= $('#id_fecha_termino').val()



    if (moment(fecha_termino).isSameOrBefore(fecha_actual)) {


            $("#mjeError").css("display","block");
            $("#textError").text("La Fecha de Término del Periodo de Validación debe ser mayor a la fecha actual.");
            return false


    }



    if ($('#id_descripcion_validacion').val() != "" && $('#id_id_periodo_seguimiento').val() != "" && $('#id_fecha_termino').val() != ""){



                $( this ).hide();
                $( '#cancelar' ).hide();
                 $( '#enviar' ).fadeIn();
                 $("#mjeError").css("display","none");
                $('#id_fecha_termino').prop( "readonly", true );
                 $('#id_id_periodo_seguimiento').prop( "readonly", true );

            }




 });
</script>